#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_WALK_RIGHT,
	PLAYER_WALK_LEFT,
	PLAYER_WALK_UP,
	PLAYER_WALK_DOWN,
	PLAYER_HIT_RIGHT,
	RLAYER_HIT_LEFT,
	PLAYER_HIT_UP,
	PLAYER_HIT_DOWN,
	PLAYER_BEHIT_LEFT,
	PLAYER_BEHIT_RIGHT,
	PLAYER_BEHIT_UP,
	PLAYER_BEHIT_DOWN,
	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/